In [ ]:
import numpy as np
#creating numpy
a=np.array([1,3,5,7])   #1D
b=np.array([(1,2,3),(4,5,6)])   #2D
c=np.array([[(2,4,6),(3,6,9)],[(5,10,15),(4,8,12)]])  #3D
print(a)
print(b)
print(c)

[1 3 5 7]
[[1 2 3]
 [4 5 6]]
[[[ 2  4  6]
  [ 3  6  9]]

 [[ 5 10 15]
  [ 4  8 12]]]


In [ ]:
#initial placeholders
x=np.zeros([4,4])
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#evenly spaced values
a=np.arange(1,30,2)#start,stop(n-1),step(n-1)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [ ]:
#linspace
b=np.linspace(1,3,8)#start,end,sample   #evenly spaced values
print(b)

[1.         1.28571429 1.57142857 1.85714286 2.14285714 2.42857143
 2.71428571 3.        ]


In [ ]:
#constant  array
x=np.full((5),4)#shape,fill value
print(x)     #1D
print(x.ndim)
y=np.full((3,2),5)
print(y)    #2D
print(y.ndim)
z=np.full((3,2,2),5)
print(z)    #3D
print(z.ndim)


[4 4 4 4 4]
1
[[5 5]
 [5 5]
 [5 5]]
2
[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]
3


In [ ]:
#2*2 identity matrix
p=np.eye(5)#dimension
print(p)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#random values
q=np.random.random((5,3)) #rows,values between 0to1
print(q)

[[0.39941954 0.51511605 0.74362469]
 [0.3277285  0.31316823 0.4407275 ]
 [0.24406769 0.91541483 0.0132761 ]
 [0.77885035 0.96351902 0.45306718]
 [0.33294024 0.23538095 0.98218442]]


In [ ]:
#shape,size,len of array
r=np.array([[(2,4,6)],
  [(3,6,9)]])
print(r.shape)
print(r.size) #no.of elememts
len(r) #len of rows

(2, 1, 3)
6


2

#math operations

In [ ]:
x=([2,4,6],[4,8,12])
y=([3,6,9],[1,2,3])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.power(x,y))
print(np.mod(x,y))

[[ 5 10 15]
 [ 5 10 15]]
[[-1 -2 -3]
 [ 3  6  9]]
[[ 6 24 54]
 [ 4 16 36]]
[[0.66666667 0.66666667 0.66666667]
 [4.         4.         4.        ]]
[[       8     4096 10077696]
 [       4       64     1728]]
[[2 4 6]
 [0 0 0]]


In [ ]:
#accesing
x=np.array([2,4,6,8])  #1D
print(x[2])
print(x[0]+x[3])
y=np.array([[3,6,9],[2,4,6]])  #2D
print(y[1,2])    #row,index

6
10
6


#Data types

In [64]:
a=np.array([2,4,6,8,10])
print(a)
print(a.dtype)

[ 2  4  6  8 10]
int64


In [90]:
#changing
x=np.array([1,2,3,4,5])
y=x.astype('f')
print(y)
print(y.dtype)


[1. 2. 3. 4. 5.]
float32


In [97]:
#methods
x=np.array([1,2,3,4,5])
y=x.copy()    #copy
x[2]=0
print(x)
print(y)
a=x.view()
x[1]=23
print(x)
print(a)
z=np.array([[2,3,4],[5,6,7]])  #shape(rows,colums)
print(z.shape)


[1 2 0 4 5]
[1 2 3 4 5]
[ 1 23  0  4  5]
[ 1 23  0  4  5]
(2, 3)


In [99]:
#reshapping
x=np.array([1,2,3,4,5,6,7,8])
y=x.reshape(2,4)
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [100]:
#sorting array
p=np.array([2,4,6,8,10,23,13,12,32])
print(np.sort(p))  #putting ordered

[ 2  4  6  8 10 12 13 23 32]


In [105]:
#slicing
q=np.array([3,6,9,12])
print(q[0:2])
print(q[-3:-1])

[3 6]
[6 9]


In [107]:
#stop
x=np.array([1,2,3,4,5,6,7,8,9])
print(x[2:9:2]) #start,end,step

[3 5 7 9]


In [108]:
#slicing 2D
z=np.array([[2,3,4],[5,6,7]])
print(z[1,0:2]) #row,index


[5 6]
